FROM erikedin/slackrest
LABEL maintainer="Erik Edin <erikedin.name@gmail.com>"

ENV PYTHONUNBUFFERED=0

COPY cert.pem /var/cert/cert.pem

COPY requirements.txt /app/requirements.txt
RUN pip3 install -v -r /app/requirements.txt

COPY . /app/



ENV REQUESTS_CA_BUNDLE=/var/cert/cert.pem
ENV WEBSOCKET_CLIENT_CA_BUNDLE=/var/cert/cert.pem

CMD ["python3", "/app/niancatslack.py"]